### ISSUE TITLE
Syntactically incorrect exception handling

### ISSUE THREAD

**Issue by fredjn** [eiffel-community/etos#128]
### Description
There is a exception catching syntactical error in the Jsontas provider in the environment provider. 

### Motivation
We don't want syntactically problematic/incorrect code ... ever.

### Exemplification
N/A

### Benefits
We get proper error messages when things go wrong

### Possible Drawbacks
None

**Comment by t-persson** [comment]
@fredjn Is this fixed?

**Comment by fredjn** [comment]
Yepp, you actually merged it yourself 😲

**Comment by t-persson** [comment]
> Yepp, you actually merged it yourself astonished

I know. This was just me poking you for not closing your issue ;)
