### ISSUE TITLE
Function tests for ETOS Test Runner

### ISSUE THREAD

**Issue by fredjn** [eiffel-community/etos#37]
### Description
Create function tests for ETOS Test Runner

### Motivation
Detect regressions from new code contributions or intermittent bugs

### Exemplification
A nightly/daily regression test suite could typically run these tests.

### Benefits
Better code and service quality, detecting regression service quickly

### Possible Drawbacks
None, if the tests are written properly and test anomalies such as flakiness is dealt with.

**Comment by t-persson** [comment]
There are tests in ETR already. Was probably fixed without closing this issue.
