### ISSUE TITLE
Helm deployment is broken!

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/etos#52]
### Description

ETOS 1.1.0 is broken. Environment provider does not start.
No rollback will be done at the moment as it is the only release we have.

### Motivation

ETOS shall not be broken

**Comment by fredjn** [comment]
It is quite unclear what is broken, when reading the issue. More details would be preferable.

**Comment by t-persson** [comment]
Environment provider does not start.

**Comment by t-persson** [comment]
Broke because of eiffel-community/etos-environment-provider#13 and the changing of the default CMD and workspace within the container.

Possible solutions would be:
- Create two Docker containers, one for workers and one for API.
- Change the "command" in the helm chart.

**Comment by t-persson** [comment]
Choosing to go with two docker containers.

**Comment by t-persson** [comment]
Fixed and verified
